// Generated by gencpp from file rm_msgs/Force_Position_State.msg
// DO NOT EDIT!


#ifndef RM_MSGS_MESSAGE_FORCE_POSITION_STATE_H
#define RM_MSGS_MESSAGE_FORCE_POSITION_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rm_msgs
{
template <class ContainerAllocator>
struct Force_Position_State_
{
  typedef Force_Position_State_<ContainerAllocator> Type;

  Force_Position_State_()
    : joint()
    , force(0.0)  {
      joint.assign(0.0);
  }
  Force_Position_State_(const ContainerAllocator& _alloc)
    : joint()
    , force(0.0)  {
  (void)_alloc;
      joint.assign(0.0);
  }



   typedef boost::array<float, 6>  _joint_type;
  _joint_type joint;

   typedef float _force_type;
  _force_type force;





  typedef boost::shared_ptr< ::rm_msgs::Force_Position_State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rm_msgs::Force_Position_State_<ContainerAllocator> const> ConstPtr;

}; // struct Force_Position_State_

typedef ::rm_msgs::Force_Position_State_<std::allocator<void> > Force_Position_State;

typedef boost::shared_ptr< ::rm_msgs::Force_Position_State > Force_Position_StatePtr;
typedef boost::shared_ptr< ::rm_msgs::Force_Position_State const> Force_Position_StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rm_msgs::Force_Position_State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rm_msgs::Force_Position_State_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rm_msgs::Force_Position_State_<ContainerAllocator1> & lhs, const ::rm_msgs::Force_Position_State_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint &&
    lhs.force == rhs.force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rm_msgs::Force_Position_State_<ContainerAllocator1> & lhs, const ::rm_msgs::Force_Position_State_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rm_msgs::Force_Position_State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rm_msgs::Force_Position_State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rm_msgs::Force_Position_State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baccacd8e94a89960b7322bda551af6d";
  }

  static const char* value(const ::rm_msgs::Force_Position_State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaccacd8e94a8996ULL;
  static const uint64_t static_value2 = 0x0b7322bda551af6dULL;
};

template<class ContainerAllocator>
struct DataType< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rm_msgs/Force_Position_State";
  }

  static const char* value(const ::rm_msgs::Force_Position_State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] joint\n"
"float32 force\n"
;
  }

  static const char* value(const ::rm_msgs::Force_Position_State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Force_Position_State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rm_msgs::Force_Position_State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rm_msgs::Force_Position_State_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint[i]);
    }
    s << indent << "force: ";
    Printer<float>::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RM_MSGS_MESSAGE_FORCE_POSITION_STATE_H
