arm:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

  gripper1_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - gripper_Link1
      - gripper_Link11
    constraints:
      goal_time: 1
      stopped_velocity_tolerance: 0.05
      gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  2.5
    action_monitor_rate: 10

  gripper2_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - gripper_Link2
      - gripper_Link22
    constraints:
      goal_time: 1
      stopped_velocity_tolerance: 0.05
      gripper_finger1_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  2.5
    action_monitor_rate: 10           

  gazebo_ros_control:
    pid_gains:
      joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      gripper_Link1:  {p: 5.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      gripper_Link11:  {p: 5.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      gripper_Link2:  {p: 5.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      gripper_Link22:  {p: 5.0, d: 1.0, i: 0.01, i_clamp: 1.0}
